[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm']

[phases.install]
cmds = ['cd server && npm ci --only=production']

[phases.build]
cmds = ['cd server && npm run build']

[start]
cmd = 'cd server && npm start'

[variables]
NODE_ENV = 'production'